config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {sessions: 'admin/sessions'}
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
    resources :calendars, only: [:index, :destroy]
  end

  root to: "homes#top"
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get "/homes/about" => "homes#about", as: "about"
  get '/mypage' => "users#mypage", as: "mypage"
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :tags, only: [:show]
  resources :users, only: [:mypage, :index, :show, :edit, :update, :destroy, :destroy]
  get "/search", to: "searches#search"
  resources :groups, only: [:create, :index, :show, :edit, :update, :destroy] do
    resources :group_users, only: [:create] do
      member do
        delete :leave
        patch :approve
        patch :reject
      end
    end
  end
  resources :calendars, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/calendars_controller.rb
class Admin::CalendarsController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def index
    @calendars = Calendar.all.order(created_at: :desc).page(params[:page])
  end

  def destroy
    calendar = Calendar.find(params[:id])
    calendar.destroy
    redirect_to admin_calendars_path,  notice: "行事予定を削除しました。"
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    @calendar_new = Calendar.new
    @events = Calendar.all
    respond_to do |format|
      format.html
      format.json {
        render json: @events.map { |e|
          {
            id: e.id,
            title: "#{e.prefecture}#{e.city}：#{e.event}",
            start: e.start_date,
            end: e.end_date,
            extendedProps: {
              editable: e.user_id == current_user.id
            }
          }
        }
      }
    end
  end

  def create
    @calendar_new = current_user.calendars.build(calendar_params)
    if @calendar_new.save
      redirect_to calendars_path, notice: "登録しました"
    else
      @events = Calendar.all
      recder :index
    end
  end

  def destroy
    @calendar = current_user.calendars.find(params[:id])
    @calendar.destroy
    redirect_to calendars_path, notice: "削除しました"
  end

  private
  def calendar_params
    params.require(:calendar).permit(:event, :prefecture, :city, :start_date, :end_date)
  end
end

app/helpers/admin/calendars_helper.rb
module Admin::CalendarsHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/admin/calendars/index.html.erb
<h1 class="mt-3 mb-3">カレンダー管理</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>行事名</th>
      <th>都道府県</th>
      <th>市区町村</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @calendars.each do |calendar| %>
      <tr>
        <td><%= calendar.id %></td>
        <td><%= calendar.event %></td>
        <td><%= calendar.prefecture %></td>
        <td><%= calendar.city %></td>
        <td><%= calendar.start_date %></td>
        <td><%= calendar.end_date %></td>
        <td><%= button_to "削除", admin_calendar_path(calendar), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= paginate @calendars %>
<br>
<%= link_to "戻る", admin_dashboards_path, class: "text-secondary link link-opacity-50-hover mt-3" %> 


<%= javascript_pack_tag 'application' %>