config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {sessions: 'admin/sessions'}
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
    resources :calendars, only: [:index, :destroy]
  end

  root to: "homes#top"
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get "/homes/about" => "homes#about", as: "about"
  get '/mypage' => "users#mypage", as: "mypage"
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :tags, only: [:show]
  resources :users, only: [:mypage, :index, :show, :edit, :update, :destroy, :destroy]
  get "/search", to: "searches#search"
  resources :groups, only: [:create, :index, :show, :edit, :update, :destroy] do
    resources :group_users, only: [:create] do
      member do
        delete :leave
        patch :approve
        patch :reject
      end
    end
  end
  resources :calendars, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_one_attached :image
  validates :name, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_group_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-iamge.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == "perfect"
      where(name: content)
    else
      where("name LIKE ?", "%#{content}%")
    end
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def index
    @groups = Group.all.order(created_at: :desc).page(params[:page])
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to admin_groups_path, notice: 'グループを削除しました'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authorize_owner, only: [:edit, :update, :destroy]
  before_action :block_guest_user, only: [:show]
  
  def create
    @group = current_user.owned_groups.build(group_params)
    @group.users << current_user

    if @group.save
      redirect_to @group, notice: "グループを作成しました"
    else
      @groups = Group.all
      flash.now[:alert] = "グループの作成に失敗しました"
      render :index
    end
  end

  def index
    @groups = Group.all
    @group = Group.new
  end

  def show
    @menbers = @group.users
  end

  def edit
  end

  def update
    if @group.update(group_params)
      flash[:notice] = "グループの編集に成功しました。"
      redirect_to @group
    else
      flash[:alert] = "グループの編集に失敗しました"
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def authorize_owner
    unless @group.owner == current_user
      redirect_to @group, alert: "この操作を行う権限がありません。"
    end
  end

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_groups.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>作成者</th>
      <th>紹介文</th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_image(100,100) %></td>
        <td>
          <% if current_user&.guest_user? %>
            <h5><%= group.name %></h5>
          <% else %>
            <h5><%= link_to group.name, group_path(group) %></h5>
          <% end %>
        </td>
        <td class="text-nowrap"><%= group.owner.name %></td>
        <td><%= group.introduction %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<h2 class="mt-3">グループ編集</h2>
<div class="row pl-3 mt-3">
  <%= form_with model: @group do |f| %>
    <div>
      <%= f.file_field :image, accept: "image/*", class: "mt-2" %>
    </div>
    <div>
      <%= f.label :name, "グループ名", class: "mt-4" %> <br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div>
      <%= f.label :introduction, "紹介文", class: "mt-4" %> <br>
      <%= f.text_area :introduction, class: "form-control" %>
    </div>
    <div class="mt-2">
      <%= f.submit "グループを編集", class: "btn btn-primary mt-4" %>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<h1 class="mt-3">ぶらり参拝会</h1>
<div class="row mt-5">
  <div class="col-md-4 pt-3">
    <% if current_user&.guest_user? %>
      <h5 class="">ゲストユーザーはグループ作成できません</h5>
    <% else %>
      <%= form_with model: @group, url: groups_path do |f| %>
        <div>
          <%= f.file_field :image, accept: "image/*", class: "mt-2" %>
        </div>
        <div>
          <%= f.label :name, "グループ名", placeholder: "1~20文字以内", class: "mt-4" %> <br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div>
          <%= f.label :introduction, "紹介文", class: "mt-4" %> <br>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="mt-2">
          <%= f.submit "グループを作成", class: "btn btn-primary mt-4" %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-7 offset-md-1 pt-3">
    <%= render "searches/form" %>
    <%= render "groups/groups", groups: @groups %>
  </div>
</div>

app/views/groups/show.html.erb
<h2 class= "text-center"><%= @group.name %></h2>
<p class="text-muted">作成者：<%= @group.owner.name %></p>
<div class="mt-3">
  <h4>紹介文</h4>
  <p><%= simple_format(@group.introduction) %></p>
</div>

<div>
  <% if @group.owner == current_user %>
    <%= link_to "編集", edit_group_path(@group), class: "btn btn-success mr-1" %> |
    <%= link_to "削除", group_path(@group), method: :delete,
        data: { confirm: "本当に削除しますか？" },
        class: "btn btn-danger ml-1" %>
  <% end %>
</div>

<% unless @group.owner == current_user || @group.users.include?(current_user) %>
  <%= button_to "参加申請する", group_group_users_path(@group), method: :post, class: "btn btn-primary" %>
<% end %>

<hr>

<% if @group.owner == current_user %>
  <h4>申請中のユーザー</h4>
  <% if @group.group_users.pending.any? %>
    <% @group.group_users.pending.each do |member| %>
      <p>
        <%= member.user.name %>
        <%= button_to "承認", approve_group_group_user_path(@group,member), method: :patch, class: "btn btn-success btn-sm" %>
        <%= button_to "拒否", reject_group_group_user_path(@group,member), method: :patch, class: "btn btn-danger btn-denger btn-sm" %>
      </p>
    <% end %>
  <% else %>
    <p>現在。申請中のユーザーはいません。</p>
  <% end %>
<% end %>
<hr>

<div class="row">
  <div class="col-md-3">
    <h4>メンバー一覧</h4>
    <ul>
      <li><strong><i class="fa-solid fa-crown"></i><%= @group.owner.name %></strong></li>
      <% @group.group_users.approved.each do |member| %>
        <li><%= member.user.name %></li>
      <% end %>
    </ul>
    <% if @group.owner != current_user && @group.users.include?(current_user) %>
      <% group_user = @group.group_users.find_by(user: current_user) %>
      <%= button_to "グループを退会する", leave_group_group_user_path(@group, group_user), method: :delete, class: "btn btn-warning mt-3" %>
    <% end %>
  </div>
  
  <div class="col-md-8 offset-md-1">
    <p class="text-center">チャット欄作成予定</p>
  </div>
</div>

<div class="mt-3">
  <%= link_to "グループ一覧に戻る", groups_path, class: "text-secondary link-underline-opacity-100-hover" %>
</div>