config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {sessions: 'admin/sessions'}
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
    resources :calendars, only: [:index, :destroy]
  end

  root to: "homes#top"
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get "/homes/about" => "homes#about", as: "about"
  get '/mypage' => "users#mypage", as: "mypage"
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :tags, only: [:show]
  resources :users, only: [:mypage, :index, :show, :edit, :update, :destroy, :destroy]
  get "/search", to: "searches#search"
  resources :groups, only: [:create, :index, :show, :edit, :update, :destroy] do
    resources :group_users, only: [:create] do
      member do
        delete :leave
        patch :approve
        patch :reject
      end
    end
  end
  resources :calendars, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:name]

  validates :name, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy 
  has_many :groups, through: :group_users
  has_many :owned_groups, class_name: 'Group', foreign_key: 'owner_id', dependent: :destroy
  has_many :calendars, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width,height)
    if profile_image.attached?
      begin
        profile_image.variant(resize_to_limit: [width, height]).processed
      rescue
        'no_image.jpg'
      end
    else
      'no_image.jpg'
    end
  end

  def self.search_for(content, method)
    if method == "perfect"
      where(name: content)
    else
      where("name LIKE ?", "%#{content}%")
    end
  end
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "おためし"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'ユーザーを退会させました'
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "ゲストユーザーでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matcing_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def mypage
    @mypage = User.find(current_user.id)
    @posts = @mypage.posts
    @like_posts = Post.joins(:likes).where(likes: { user_id: current_user.id})
  end

  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィールの編集に成功しました。"
      redirect_to mypage_path
    else
      flash[:alert] = "プロフィールの編集に失敗しました"
      render :edit
    end
  end

  def destroy
    user = User.find(current_user.id)
    user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matcing_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def ensure_guest_user
    @mypage = User.find(params[:id])
    if @mypage.guest_user?
      redirect_to mypage_path(current_user), notice: "ゲストユーザーはプロフィール編集できません。"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>お名前</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "詳細", user_path(user.id), class: "btn btn-outline-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="row">
  <div class="d-flex justify-content-center">
    <h1>プロフィール編集</h1>
  </div>
</div>
<div class="row">
  <%= form_with model: @user do |f| %>
    <label for="inputName">名前</label><br>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control" %><br>
    <label for="inputIntroduction">自己紹介文</label><br>
    <%= f.text_area :introduction, class: "form-control" %> <br>
    <label for="inputImage">プロフィール画像</label><br>
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
    <%= f.submit "編集を保存", class: "btn btn-outline-success mt-5" %>
  <% end %>
</div>
<div class="row">
  <% if @user == current_user %>
    <%= link_to "退会", user_path(@user), method: :delete, "data-confirm" => "本当に退会しますか？", class: "btn btn-outline-danger mt-3" %>
  <% end %>
</div>
    <br>
<div class="row">
  <%= link_to "戻る", mypage_path, class: "text-secondary link-underline-opacity-100-hover" %>
</div>

app/views/users/index.html.erb
<h2 class="mt-4">参拝者一覧</h2>
<div class="mb-3">
  <%= render "searches/form" %>
</div>

<%= render "users/users", users: @users %>
<div class="pagination-wrapper text-center mb-3">
  <%= paginate @users %>
</div>

<div class="row">
  <%= link_to "一覧へ戻る", posts_path, class: "text-secondary link-underline-opacity-100-hover" %>
</div>

app/views/users/mypage.html.erb
<div class="row">
  <h1 class="mb-3">私の参拝帖</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>
        <%= link_to edit_user_path(@mypage) do %>
          <%= image_tag @mypage.get_profile_image(100,100) %>
        <% end %>
      </th>
      <th><h3><%= @mypage.name %></h3></th>
    </tr>
    <tr>
      <th></th>
      <th><%= @mypage.introduction %></th>
    </tr>
  </thead>
</table>

<br>
<% unless @mypage.guest_user? %>
  <div class="row">
    <%= link_to edit_user_path(@mypage), class: "btn btn-outline-secondary btn-block mt-3" do %>
      <i class="fa-solid fa-pen-to-square"></i>
      プロフィールを編集する
    <% end %>
  </div>

  <div class="row">
    <%= link_to new_post_path(@post_new), class: "btn btn-outline-primary btn-block mt-2" do %>
      <i class="fa-solid fa-file-pen"></i>
      新しい記を綴る
    <% end %>
  </div>
<% end %>


<div class="row mt-5">
  <ul class="nav nav-tabs" id="postTabs">
    <li class="nav-item">
      <a class="nav-link active" data-tab="my-posts">私の参拝帖</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-tab="liked-posts">いいねした投稿</a>
    </li>
  </ul>
</div>

<div id="my-posts" class="tab-content active mt-3">
  <div class="row d-flex justify-content-center">
    <h3 class="mt-5 ">参拝記録</h3>
    <% if current_user&.guest_user? %>
      <h5 class="mt-3">ゲストユーザーはご利用できません</h5>
    <% else %>
      <%= render "searches/form" %>
    <% end %>
    <table class="table">
      <%= render @posts %>
    </table>
  </div>
</div>

<div id="liked-posts" class="tab-content mt-3" style="display:none;">
  <table class="table">
    <% if current_user&.guest_user? %>
      <h5 class="mt-5">ゲストユーザーはご利用できません</h5>
    <% else %>
      <% @like_posts.each do |post| %>
        <%= render post %>
      <% end %>
    <% end %>
  </table>
</div>

<div class="row mt-5">
  <%= link_to "一覧へ戻る", posts_path, class: "text-secondary link-underline-opacity-100-hover mt-3" %>
</div>

app/views/users/show.html.erb
<div>
  <h1> <%= @user.name %> さんの参拝記</h1>
  <%= image_tag @user.get_profile_image(100,100) %>
</div>

<table class="table">
  <%= render @posts %>
</table>

<%= link_to "一覧に戻る", posts_path, class: "text-secondary link-underline-opacity-100-hover" %>