config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {sessions: 'admin/sessions'}
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
    resources :calendars, only: [:index, :destroy]
  end

  root to: "homes#top"
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get "/homes/about" => "homes#about", as: "about"
  get '/mypage' => "users#mypage", as: "mypage"
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :tags, only: [:show]
  resources :users, only: [:mypage, :index, :show, :edit, :update, :destroy, :destroy]
  get "/search", to: "searches#search"
  resources :groups, only: [:create, :index, :show, :edit, :update, :destroy] do
    resources :group_users, only: [:create] do
      member do
        delete :leave
        patch :approve
        patch :reject
      end
    end
  end
  resources :calendars, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :shirine_name, presence: true
  validates :address, presence: true
  validates :body, presence: true, length: {maximum: 500}
  validates :parking, inclusion: {in: ['unavailable','available']}
  validates :shirine_stamp, inclusion: {in: ['no_stamp','has_stamp']}
  validates :seasonal_stamp, inclusion: {in:['regular', 'january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december', 'nostamp']}

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/No_神社image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == "perfect"
      where(shirine_name: content)
    else
      where("shirine_name LIKE ?", "%#{content}%")
    end
  end

  geocoded_by :address
  after_validation :geocode

  def favorited_by?(user)
    likes.exists?(user_id: user.id)
  end

  enum parking: { unavailable: 0, available: 1}
  enum shirine_stamp: { no_stamp: 0, has_stamp: 1}
  enum seasonal_stamp: {regular: 0, january: 1, february: 2, march: 3, april: 4, may: 5, june: 6, july: 7, august: 8, september: 9, october: 10, november: 11, december: 12, nostamp: 13}

  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!
  
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: '投稿を削除しました'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matcing_login_user, only: [:edit, :update]
  before_action :block_guest_user, only: [:new, :create, :edit, :update]
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tag_name].split(/[[:blank:],、]+/).uniq

    if @post.save
      tag_list.each do |tag_name|
        tag = Tag.find_or_create_by(name: tag_name)
        @post.tags << tag
      end
      flash[:notice] = "投稿に成功しました。"
      redirect_to post_path(@post.id)
    else
      @user = current_user.id
      flash[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def index
    respond_to do |format|
      format.html do
        @posts = Post.order(created_at: :desc).page(params[:page])
      end
      format.json do
        @posts = Post.includes(:user).order(created_at: :desc)
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(',')
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:tag_name].split(/[[:blank:],、]+/).uniq if params[:post][:tag_name].present?
    
    if @post.update(post_params)
      if tag_list
        @post.tags.clear
        tag_list.each do |tag_name|
          tag = Tag.find_or_create_by(name: tag_name)
          @post.tags << tag
        end
      end
      flash[:notice] = "編集に成功しました。"
      redirect_to post_path(@post.id)
    else
      flash[:alert] = "編集に失敗しました"
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit( :shirine_name, :body, :address, :latitude, :longitude, :parking, :shirine_stamp, :seasonal_stamp, :image)
  end

  def is_matcing_login_user
    @post = Post.find(params[:id])
    @user = @post.user
    unless @user.id == current_user.id
      redirect_to posts_path
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>

  <h4 class="pt-3">写真</h4>
  <%= f.file_field :image, accept: "image/*", required: false, class: "pb-3" %>
  <h4>神社の名前</h4>
  <%= f.text_field :shirine_name, class: "form-control", id: "shirine_name" %>
  <h4 class="mt-2">住所</h4>
  <div class="input-group mb-3 mt-4">
      <div class="input-group-prepend">
        <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-tenge-sign"></i></span>
      </div>
      <%= text_field_tag :zipcode, nil, class: "form-control", placeholder: "郵便番号" %>
    </div>
    <div class="input-group mb-3 mt-4">
      <div class="input-group-prepend">
        <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-location-dot"></i></span>
      </div>
      <%= f.hidden_field :latitude, id: "post_latitude" %>
      <%= f.hidden_field :longitude, id: "post_longitude" %>
      <%= f.text_field :address, class: "form-control", placeholder: "住所", id: "post_address" %>
    </div>
  <h4 class="mt-2">本文</h4>
  <%= f.text_area :body, class: "form-control", placeholder: "感想や御由緒などを書きましょう。", id: "body" %></br>
  
  <h4>駐車場の有無</h4>
  <%= f.radio_button :parking, Post.parkings.key(0),id: "post_parking_0" %>
  <%= f.label :parking, Post.parkings_i18n[:unavailable], value: Post.parkings.key(0), for: "post_parking_0" %>
  <%= f.radio_button :parking, Post.parkings.key(1), id: "post_parking_1" %>
  <%= f.label :parking, Post.parkings_i18n[:available], value: Post.parkings.key(1), for: "post_parking_1" %></br>
  <h4>御朱印の有無</h4>
  <%= f.radio_button :shirine_stamp, Post.shirine_stamps.key(0), id: "post_shirine_stamp_0" %>
  <%= f.label :shirine_stamp, Post.shirine_stamps_i18n[:no_stamp], value: Post.shirine_stamps.key(0), for: "post_shirine_stamp_0" %>
  <%= f.radio_button :shirine_stamp, Post.shirine_stamps.key(1), id: "post_shirine_stamp_1" %>
  <%= f.label :shirine_stamp, Post.shirine_stamps_i18n[:has_stamp], value: Post.shirine_stamps.key(1), for: "post_shirine_stamp_1" %></br>
  <h4>季節限定の御朱印</h4>
  <%= f.select :seasonal_stamp, options_for_select(Post.seasonal_stamps_i18n.invert), class: "mb-5" %><br>
  <br>
  <%= f.label :tag_name, "タグ（スペースまたはカンマ区切り）" %>
  <%= f.text_field :tag_name, class: "form-control", placeholder: "例）八幡宮, 神宮, 大社", value: @tag_list %>

  <div class="mt-3">
    <% if post.new_record? %>
      <%= f.submit '投稿', class: "my-5 btn btn-outline-primary" %>
    <% else %>
      <%= f.submit '保存', class: "my-5 btn btn-outline-success" %>
    <% end %>
  </div>
<% end %><br>

<%= javascript_pack_tag "jpostal",  'data-turbolinks-track': 'reload' %>

app/views/posts/_list.html.erb
<table>
  <thead>
    <tr>
      <th></th>
      <th>神社名</th>
      <th>記録</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= link_to post_path(@post) do %>
          <%= image_tag @post.get_image(200,200) %>
        <% end %>
      </td>
      <td>
        <%= @post.shirine_name %>
      </td>
      <td>
        <%= @post.body %>
      </td>
    </tr>
  </tbody>
</table>

app/views/posts/_post.html.erb
<thead>
  <tr>
    <th>
      <%= link_to post_path(post.id) do %>
        <%= image_tag post.get_image(200,200) %>
      <% end %>
    </th>
    <th class="text-nowrap"><%= post.shirine_name %></th>
  </tr>
  <tr>
    <th><%= post.address %></th>
  </tr>
  <tr><th><%= post.body %></th></tr>
  <tr>
    <th><%= post.parking_i18n %></th>
    <th><%= post.shirine_stamp_i18n %></th>
  </tr>
  <tr>
    <th><%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %></th>
  </tr>
</thead>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
  <%= link_to post_path(post) do %>
    <%= image_tag post.get_image(300,300) %>
  <% end %>
  <table class="table table-hover">
    <tr>
      <th>
        <%= post.shirine_name %>
        <% if post.tags.any? %>
          <div class="tags">
            <% post.tags.each do |tag| %>
              <%= link_to tag.name, tag_path(tag), class: "badge bg-primary text-light" %>
            <% end %>
          </div>
        <% end %>
      </th>
    </tr>
    <tr>
      <th>
        <%= link_to post_path(post.id) do %>
          <span>
            <i class="fa-solid fa-comment"></i>
            <%= post.post_comments.count %>
          </span>
        <% end %>
      </th>
      <th>
        <div class="like-area-<%= post.id %>">
          <%= render "likes/like", post: post %>
        </div>
      </th>
    </tr>
    <tr>
      <th>
        <%= post.address %>
      </th>
      <th></th>
    </tr>
    <tr>
      <th>
        <%= post.body %>
      </th>
      <th></th>
    </tr>
    <tr>
      <th>
        <%= post.parking_i18n %>
      </th>
      <th>
        <%= post.shirine_stamp_i18n %>
      </th>
    </tr>
    <tr>
      <th>
        <%= link_to user_path(post.user_id) do %>
          <%= image_tag post.user.get_profile_image(100,100) %>
        <% end %>
      </th>
      <th>
        <%= post.user.name %>
      </th>
    </tr>
  </table>
<% end %>

app/views/posts/edit.html.erb
<h1>参拝記録編集</h1>

<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="row">
  <div class="col-md-4">
    <%= render 'form', post: @post %>
  </div>
  <div class="col-md-7 offset-md-1">
    <div id="map_form" style="width:100%; height:500px;"></div>
  </div>
</div>

<%= link_to "一覧へ戻る", posts_path, class: "text-secondary link-underline-opacity-100-hover" %> |
<%= link_to "参拝記へ戻る", post_path, class: "text-secondary link-underline-opacity-100-hover" %>

<%= javascript_pack_tag 'map_form', 'data-turbolinks-track': 'reload' %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-7">
    <h1>地図</h1>
    <div class="mt-3">
      <div id="map" style="width:100%; height:60vh; position:sticky; top:0;"></div>
    </div>
  </div>
  
  <div class="col-md-5" style="height:100vh; overflow-y:auto; position:relative;">
    <div style="position:sticky; top:0; background:white; z-index:10; padding-top:10px; padding-bottom:10px;">
      <div class="sticky-top bg-white p-2 shadow-sm">
        <h1>投稿一覧</h1>
        <%= render "searches/form" %>
        <br>
        <div class="pagination-wrapper text-center">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
    <div class="text-truncate">
      <%= render "posts/posts", posts: @posts %>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'map_index', 'data-turbolinks-track': 'reload' %>

app/views/posts/new.html.erb
<div class="row-center">
  <h1 class="pt-3">神社の投稿をしよう！</h1>

  <% if @post.errors.any? %>
    <%= @post.errors.count %>件のエラーが発生しました
    <ul class="text-danger">
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<div class="row">
  <div class="col-md-4">
    <%= render 'form', post: @post %>
  </div>
  <div class="col-md-7 offset-md-1">
    <div id="map_form" style="width:100%; height:500px;"></div>
  </div>
</div>
<div class="row">
  <%= link_to "戻る", posts_path, class: "text-secondary link-underline-opacity-100-hover mt-3" %> 
</div>

<%= javascript_pack_tag 'map_form', 'data-turbolinks-track': 'reload' %>

app/views/posts/show.html.erb
<div class="row">
  <h1>参拝記</h1>
  
  <table class="table table-hover">
    <thead>
      <tr>
        <th>
          <%= link_to user_path(@user) do %>
            <%= image_tag @user.get_profile_image(100,100) %>
          <% end %>
        </th>
        <th class="text-nowrap">
          <%= link_to @post.user.name, user_path(@user.id) %>
        </th>
      </tr>
      <tr>
        <th>
          <p class="">神社の名前：<%= @post.shirine_name %></p>
          <% if @post.tags.any? %>
            <p>タグ：
              <% @post.tags.each do |tag| %>
                <%= link_to tag.name, tag_path(tag), class: "badge rounded-pill bg-primary text-light" %>
              <% end %>
            </p>
          <% end %>
        </th>
        <th><%= render "likes/like", post: @post %></th>
      </tr>
      <tr>
        <th><span><i class="fa-solid fa-location-dot"></i><%= @post.address %></th>
      </tr>
      <tr>
        <th>駐車場の有無：<%= @post.parking_i18n %></th>
      </tr>
      <tr>
        <th>御朱印の有無：<%= @post.shirine_stamp_i18n %></th>
      </tr>
      <tr>
        <th>季節限定の御朱印： <%= @post.seasonal_stamp_i18n %></th>
      </tr>
      <tr>
        <th>
          <span class="text-wrap"><%= @post.body %></span>
        </th>
      </tr>
      <tr>
        <th>
          <p>参拝日：<%= @post.created_at.strftime('%Y/%m/%d') %></p>
        </th>
      </tr>
      <tr>
        <th><%= image_tag @post.get_image(500,500) %></th>
        <% if @post.user == current_user %>
          <th><%= link_to "削除", post_path(@post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-outline-danger" %></th>
        <% end %>
      </tr>
      <tr>
        <th>
          <p><%= @post.post_comments.count %> 件のコメント</p>
          <% @post.post_comments.each do |post_comment| %>
            <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
            <%= post_comment.user.name %>：
            「 <%= post_comment.comment %> 」
            <%= post_comment.created_at.strftime('%Y/%m/%d') %>
            <% if post_comment.user == current_user %>
              <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, "data-confirm" => "本当に削除しますか？" %>
            <% end %>
          <% end %>
          <div>
            <% if current_user&.guest_user? %>
              <h5 class="mt-3">ゲストユーザーはコメントの投稿ができません</h5>
            <% else %>
              <%= form_with model: [@post, @post_comment] do |f| %>
                <%= f.text_area :comment, rows: '5', placeholder: "コメントする", class: "form-control" %><br>
                <%= f.submit "送信", class: "btn btn-outline-success" %>
              <% end %>
            <% end %>
          </div>
        </th>
      </tr>
    </thead>
  </table>
  <div class="col mt-5">
    <p>＜<%= link_to "一覧へ戻る", posts_path, class: "text-secondary link-underline-opacity-100-hover" %> | 
    <% if @post.user == current_user %>
      <%= link_to "参拝記録を編集", edit_post_path, class: "text-secondary link-underline-opacity-100-hover" %>
    <% end %></p>
  </div>
</div>